#!/bin/bash
case "$1" in
	"start") minty-colors-process;;
	"stop") killall minty-colors-process;;
	"help") man minty-colors;;
	"gui") minty-colors-gui;;
	*) nohup minty-colors-process > /dev/null 2>&1 &;;
esac
