[Desktop Entry]
Type=X-GNOME-Metatheme
Name=05-Crunchy-green
Comment=Variant of Ambiance theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=05-Crunchy-green
MetacityTheme=05-Crunchy-green
GtkColorScheme=base_color:#FAFAFA,fg_color:#4c4c4c,tooltip_fg_color:white,selected_bg_color:#70AE6C,selected_fg_color:white,text_color:#3C3C3C,bg_color:#F2F1F2,tooltip_bg_color:#373b3c,link_color:#70AE6C,light_grey:#cdcdcd
IconTheme=Mint-X-Dark
CursorTheme=default
ButtonLayout=close,minimize,maximize:menu
