#!/bin/bash
THEMENAME="Cinnamox-Kashmir-Blue";
DIRECTORY="/home/$USER/.themes/$THEMENAME/cinnamon/";
LIGHTBG="#577584";
LOWTRANSLIGHTBG="rgba(87, 117, 132, 0.8)";
MODTRANSLIGHTBG="rgba(87, 117, 132, 0.65)";
HIGHTRANSLIGHTBG="rgba(87, 117, 132, 0.5)";
DARKBG="#28343a";
LOWTRANSDARKBG="rgba(40, 52, 58, 0.9)";
MODTRANSDARKBG="rgba(40, 52, 58, 0.75)";
HIGHTRANSDARKBG="rgba(40, 52, 58, 0.6)";
cd $DIRECTORY;
if ! grep -q "$THEMENAME" cinnamon.css; then
	echo "There is a problem.";
	echo "Cannot find the cinnamon.css file for $THEMENAME in the working directory.";
	echo "The script should be launched from within $DIRECTORY";
	read -p "Press enter to exit script.";
	exit 1;
fi
if grep -q "No transparency" cinnamon.css && grep -q "$LIGHTBG" cinnamon.css; then
	CURRENT="No transparency";
	LIGHTBGC=$LIGHTBG;
	DARKBGC=$DARKBG;
	VARIANT=("Low transparency" "Moderate transparency" "High transparency" "Quit");
	cp cinnamon.css cinnamon_original.css;
elif grep -q "Low transparency" cinnamon.css && grep -q "$LOWTRANSLIGHTBG" cinnamon.css; then
	CURRENT="Low transparency";
	LIGHTBGC=$LOWTRANSLIGHTBG;
	DARKBGC=$LOWTRANSDARKBG;
	VARIANT=("No transparency" "Moderate transparency" "High transparency" "Quit");
elif grep -q "Moderate transparency" cinnamon.css && grep -q "$MODTRANSLIGHTBG" cinnamon.css; then
	CURRENT="Moderate transparency";
	LIGHTBGC=$MODTRANSLIGHTBG;
	DARKBGC=$MODTRANSDARKBG;
	VARIANT=("No transparency" "Low transparency" "High transparency" "Quit");
elif grep -q "High transparency" cinnamon.css && grep -q "$HIGHTRANSLIGHTBG" cinnamon.css; then
	CURRENT="High transparency";
	LIGHTBGC=$HIGHTRANSLIGHTBG;
	DARKBGC=$HIGHTRANSDARKBG;
	VARIANT=("No transparency" "Low transparency" "Moderate transparency" "Quit");
else
	echo "Cannot confirm the current transparency of Cinnamox-Kashmir-Blue. Something is wrong.";
	read -p "Press enter to exit script.";
	exit 1;
fi
echo "Hello $USER, this script allows you to set the transparency of $THEMENAME.";
echo "The current transparency of $THEMENAME is $CURRENT.";
echo "Select a alternative transparency level by selecting 1, 2, or 3 and then press enter,";
echo "or select 4 and press enter to quit.";
select CHOICE in "${VARIANT[@]}";
do
    case $CHOICE in 
    "No transparency")
		LIGHTBGN=$LIGHTBG; DARKBGN=$DARKBG;;
    "Low transparency")
		LIGHTBGN=$LOWTRANSLIGHTBG; DARKBGN=$LOWTRANSDARKBG;;
    "Moderate transparency")
		LIGHTBGN=$MODTRANSLIGHTBG; DARKBGN=$MODTRANSDARKBG;; 
    "High transparency")
		LIGHTBGN=$HIGHTRANSLIGHTBG; DARKBGN=$HIGHTRANSDARKBG;;
	"Quit")
		cd; exit;;
    *) echo "Invalid option. Try another one."; continue;;
    esac
    break
done
cp cinnamon.css cinnamon_last.css;
sed -i "s/$LIGHTBGC/$LIGHTBGN/g" cinnamon.css;
sed -i "s/$DARKBGC/$DARKBGN/g" cinnamon.css;
sed -i "s/$CURRENT/$CHOICE/g" cinnamon.css;
echo "Theme updated!";
if which gsettings > /dev/null; then
	echo "Now activating $THEMENAME - $CHOICE.";
	gsettings set org.cinnamon.theme name 'cinnamon';
	gsettings set org.cinnamon.theme name "$THEMENAME";
else
	echo "If $THEMENAME is already active then press Ctrl-Alt-Esc to reload cinnamon and the theme.";
	echo "if $THEMENAME is not active go to the Themes App and set $THEMENAME as your desktop theme.";
	echo "But first exit the script!";
fi
read -p "Press enter to exit the script.";
cd;
exit
