.TH "minty-colors" 1 "24-09-2012" minty-colors

.SH NAME
minty-colors \- chameleon theme for cinnamon

.SH DESCRIPTION
Minty Colors is a chameleon theme for Cinnamon. It can change colors according to the current GTK theme, current wallpaper (uses imagemagick to get color) or a user defined color. Also various other aspects of the theme are customizable.

.SH CUSTOMISATION
After installation, run
.B minty-colors
from the terminal to start the process. The process will run in the background, so you won't see any outputs. It will also make a theme basing upon the template and default configuration.

To choose the theme, or run the following commands in Terminal,

gsettings set org.cinnamon.theme name name
.B minty-colors

A process runs in the background which detects any change and reloads the theme accordingly. Everything will be automatic.

You can launch the GUI from the menu which lets you customise various aspects of the the theme. It will take few seconds for the changes to be applied.

.SH NOTES
The configuration file is automatically created and replaced every time you change the configuration. It should not be edited by hand.

.SH CAVEATS
It will usually take few seconds to apply new configuration. When applying the new configuration, the theme is reloaded, and Cinnamon may freeze if you do things really fast when reloading the theme.

.SH AUTHOR
Satyajit Sahoo <satyajit.happy@gmail.com>
