[Desktop Entry]
Name=Light-Dark-Balance
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Light-Dark-Balance
MetacityTheme=Light-Dark-Balance
IconTheme=elementary-mono-dark
GtkColorScheme=base_color:#ffffff,fg_color:#4c4c4c,tooltip_fg_color:#ffffff,selected_bg_color:#808080,selected_fg_color:#FFFFFF,text_color:#3C3C3C,bg_color:#E7E5E4,tooltip_bg_color:#000000,link_color:#DD4814
CursorTheme=DMZ-White
CursorSize=18
